apiVersion: v1 # Specifies the API version for the Service resource
kind: Service # Declares that this is a Service resource

metadata:
  name: karsajobs-ui # Name of the service; used for internal DNS and referencing

spec:
  type: NodePort # Exposes the service on each Node's IP at a static port

  selector:
    app: karsajobs-ui # Selects the pods with the label "app: karsajobs-ui"

  ports:
    - protocol: TCP # Specifies the communication protocol
      port: 8000 # Port that the service exposes inside the cluster
      targetPort: 8000 # Port on the container that receives the traffic
      nodePort: 30007 # Static external port on the node
