apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi # Storage size
  accessModes:
    - ReadWriteOnce # Single node read-write
  hostPath:
    path: /data/db # Same path as Docker Compose volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Matches PersistentVolume capacity