apiVersion: apps/v1
kind: StatefulSet # Declares that this is a StatefulSet
metadata:
  name: mongo # Name of the StatefulSet
spec:
  serviceName: mongo # Name of the headless service
  replicas: 1 # Desired pod replicas
  selector:
    matchLabels:
      app: mongo # Label selector to identify which pods this StatefulSet manages
  template: # Pod template for the StatefulSet
    metadata:
      labels:
        app: mongo # Label for the pod
    spec:
      containers:
        - name: mongo # Name of the container
          image: mongo # MongoDB image to use
          ports:
            - containerPort: 27017 # Expose default MongoDB port

          volumeMounts:
            - name: mongo-storage # Name of the volume mount
              mountPath: /data/db # Mount path inside the container
            - name: mongo-secret
              mountPath: /etc/mongo-credentials
              readOnly: true
            - name: mongo-config    # ConfigMap volume mount
              mountPath: /config    # Mount path as required
              readOnly: true

          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE # Environment variables pointing to file
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE # Environment variables pointing to file
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD

          command:              #Use the config file
            - mongod
            - --config
            - /config/mongo.conf
                  
      volumes:
        - name: mongo-storage # Use PVC
          persistentVolumeClaim:
            claimName: mongo-pvc # Reference to PVC
        - name: mongo-secret
          secret:
            secretName: mongo-secret
        - name: mongo-config    # ConfigMap volume
          configMap:
            name: mongo-config
            