apiVersion: v1 # Specifies the API version for the Service resource
kind: Service # Declares that this resource is a Service

metadata:
  name: mongo # Name of the service
  labels:
    app: mongo # Labels to identify the service

spec:
  type: ClusterIP # Specifies the type of service

  selector:
    app: mongo # Targets pods

  ports:
    - name: mongodb # A name for the port (optional, but useful for referencing)
      protocol: TCP # Communication protocol
      port: 27017 # Port exposed by the service inside the cluster
      targetPort: 27017 # Port on the container that receives traffic from the service

  clusterIP: None # Setting ClusterIP to None