apiVersion: v1 # Specifies the API version for the ConfigMap resource
kind: ConfigMap # Declares that this resource is a ConfigMap

metadata:
  name: mongo-config # Name of the ConfigMap

data:
  # MongoDB configuration file contents
  mongo.conf: |
    storage:
      dbPath: /data/db      # Directory where MongoDB stores its data

    net:
      bindIp: 0.0.0.0       # MongoDB will listen on all network interface
      port: 27017           # The default port on which MongoDB listens
      
    security:
      authorization: enabled
